### ISSUE TITLE
Drush make hasznalata acquia cloudban

### ISSUE THREAD

**Issue by yorkhu** [Drupalaton/drupalaton_profile#1]
Megvizsgalni a mostani drush make alapu build rendszert, hogy lehet atultetni az acquia cloudban.
Hasznos linkek:
https://www.acquia.com/blog/custom-distributions-acquia-cloud-part-1-drush-make
https://www.acquia.com/blog/custom-distributions-acquia-cloud-part-2-updating-drush-make

**Comment by yorkhu** [comment]
Sikerult megcsinalni?

**Comment by csakiistvan** [comment]
nem lehet
