### ISSUE TITLE
Social share kép fix

### ISSUE THREAD

**Issue by zsofimajor** [Drupalaton/drupalaton_profile#24]
Most Ruben jön be az URL alap megosztásánál: http://www.awesomescreenshot.com/image/344701/af11ce6f182591026fe5c92bbb97ab34

A Drupalaton logó jó lesz helyette.

**Comment by csakiistvan** [comment]
fixed, http://2015.drupalaton.hu/workshop/storing-data-with-drupal8

![screen shot 2015-06-22 at 23 43 48](https://cloud.githubusercontent.com/assets/2457274/8293847/90d8dd4e-1938-11e5-81eb-66aa2986852d.png)

**Comment by zsofimajor** [comment]
csinatos!
