### ISSUE TITLE
Legordulo menu

### ISSUE THREAD

**Issue by yorkhu** [Drupalaton/drupalaton_profile#28]
A legordulo menu elos (menuben is latszo) menupontja nem kattinthato.
Megoldas itt: https://gist.github.com/csakiistvan/305858b9c23e191388d6
Be kellene rakni a megfelelo helyre.

**Comment by csakiistvan** [comment]
kész, csak át kell dobni staging, live kornyezetre

http://drupalatondev.prod.acquia-sites.com
