### ISSUE TITLE
Tamogato logok

### ISSUE THREAD

**Issue by yorkhu** [Drupalaton/drupalaton_profile#29]
A tamogatok oldalan eleg benan nez ki a logo.
Idezet a bejelentesbol:
plz. rendezzuk mondjuk jobbra a logot, mert eleg nyomin nez ki, hogy nincs eltartas a logo korul:
http://2015.drupalaton.hu/brainsum
Ha nem tud atvandorolni, akkor legyen az eltartas folotte+alatta 30px.

**Comment by csakiistvan** [comment]
fixed
