### ISSUE TITLE
Session CT-hez rendes display mode

### ISSUE THREAD

**Issue by yorkhu** [Drupalaton/drupalaton_profile#3]
Jelenleg a body-ba kell berakni mindent manualisan, ezt meg kellene szuntetni.
Helyette formazott diplay mode.

**Comment by yorkhu** [comment]
Szukseg lenne a teaser es a full nezet kialakitasara. A teaser kerulne a session oldalra, a full nezet meg be lenne linkelve. Valamint kellene egy olyan display is amit ki tudunk rakni a fooldalra, hasonloan az elozo evekhez.

**Comment by csakiistvan** [comment]
Ez kész?

**Comment by yorkhu** [comment]
Ez var rad, a sitebuildet megcsinaltam csak be kell formazni a contentet, lsd. scheduler page.

**Comment by csakiistvan** [comment]
http://drupalatondev.prod.acquia-sites.com/schedule már csak ki kell tenni élesbe akkor
