### ISSUE TITLE
Mobil nézeten hiányzik a dátum

### ISSUE THREAD

**Issue by zsofimajor** [Drupalaton/drupalaton_profile#30]
![true png](https://cloud.githubusercontent.com/assets/4191750/12109606/a2ec7ffa-b383-11e5-8347-d846c8ad2b8d.jpeg)

**Comment by csakiistvan** [comment]
http://drupalatondev.prod.acquia-sites.com/

**Comment by zsofimajor** [comment]
Gomb van, naptárba nem teszi be.

**Comment by csakiistvan** [comment]
Segígts kérlek hogy mi történik, mert nekem betette

<img width="616" alt="screen shot 2016-01-07 at 12 20 27" src="https://cloud.githubusercontent.com/assets/2457274/12169497/1b166430-b539-11e5-958a-b54142e006fa.png">

**Comment by zsofimajor** [comment]
Mehet élesre, már működik.
