### ISSUE TITLE
Sponsor oldalon

### ISSUE THREAD

**Issue by yorkhu** [Drupalaton/drupalaton_profile#33]
A sponsor oldalon az extra csomagokat jobban elvalasztani a sima csomagoktol.

**Comment by aboros** [comment]
azt javaslom, hogy a sponsor packages cím legyen h1 és kapjon .title osztályt, plusz még ~50px margin-top. 
![sponsor_packages___drupalaton](https://cloud.githubusercontent.com/assets/359641/15246547/ec6cf246-190d-11e6-9ada-ec17e03dbf2a.jpg)
ez markup változás lenne, gondolom a node bodyban. ha már ott járunk, jó lenne a special packages részt egy divbe tenni, hogy könnyen el lehessen tüntetni ezeknek a csomagoknak a .pack-name -jéből a padding-top -ot ami itt nem kell, csak a rendes csomagoknál.

**Comment by yorkhu** [comment]
A h1 nem jo otlet, hiszen van mar h1 az oldalon.

**Comment by yorkhu** [comment]
Atirtam h2-re legyszives tegyel ra erre egy kis formazast.
