### ISSUE TITLE
Header átalakítása, hogy beférjen a diamond sponsor

### ISSUE THREAD

**Issue by zsofimajor** [Drupalaton/drupalaton_profile#37]
Ehhez a cover képet át kell méretezni. Lásd 2015.drupalaton.hu

**Comment by csakiistvan** [comment]
![screen shot 2016-06-30 at 12 35 55](https://cloud.githubusercontent.com/assets/2457274/16485476/41dc7374-3ebf-11e6-9cd6-60d3c2032824.png)

csak úgy ha sokkal kissebb a felirat a fejlécben, úgy oké? 2015-ben a logó kissebb volt mint idén, vagy egységes lesz és akkor lehet ugyanaz

**Comment by csakiistvan** [comment]
![screen shot 2016-06-30 at 12 43 18](https://cloud.githubusercontent.com/assets/2457274/16485624/40bb507c-3ec0-11e6-8edd-537f99814571.png)

teljes screen view

**Comment by zsofimajor** [comment]
Mehet így ki @csakiistvan
