### ISSUE TITLE
Footer FB share után braziljs-foundation a sharer

### ISSUE THREAD

**Issue by zsofimajor** [Drupalaton/drupalaton_profile#38]
<img width="487" alt="screen shot 2016-06-30 at 12 46 48" src="https://cloud.githubusercontent.com/assets/4191750/16485747/d619ef98-3ec0-11e6-9ffd-d02965c5b1d0.png">

Valami miatt a sharerbe ez kerül bele, nem tudom, mi lehet az oka, de ki kéne vizsgálni.

**Comment by ChandeepKhosa** [comment]
I just tested this now and it is still an issue. I recommend using AddThis module for social sharing to avoid this
