### ISSUE TITLE
Anchor a session lista tetejére

### ISSUE THREAD

**Issue by zsofimajor** [Drupalaton/drupalaton_profile#41]
Hogy a /schedule oldalon a sessionök listájának az elejére tudjunk linkelni.

**Comment by csakiistvan** [comment]
így? http://2016.drupalaton.hu/schedule#top

**Comment by zsofimajor** [comment]
Majdnem így, a session lista elejére kéne ugrani (Sessions címmel kezdődik).

**Comment by csakiistvan** [comment]
Hirtelen release nélkül csak ilyen csúnyán lehet http://2016.drupalaton.hu/schedule#page-title de majd ránézek
