### ISSUE TITLE
Footerben két sorba törik a share szöveg

### ISSUE THREAD

**Issue by zsofimajor** [Drupalaton/drupalaton_profile#42]
Chrome: 58.0.3029.81
Firefox: 46.0.1
Safari: 10.0.3

Mac OS Sierra, 10.12.3

<img width="1363" alt="screen shot 2017-05-04 at 20 00 58" src="https://cloud.githubusercontent.com/assets/4191750/25770995/9e1b62e8-3244-11e7-8f95-43804555b9d0.png">

**Comment by sajt** [comment]
Commitoltam.

**Comment by segi** [comment]
@zsofimajor zarhato?

**Comment by zsofimajor** [comment]
igenigen
