### ISSUE TITLE
Szponzor logok a footerbe

### ISSUE THREAD

**Issue by zsofimajor** [Drupalaton/drupalaton_profile#46]
Van már gold szponzorunk a weboldalon, de nem jelenik meg a footerben. Ez nagyon fontos lenne, hogy minél hamarabb megjavuljon.

**Comment by segi** [comment]
Hol kellene megjelennie? Nekem most kint van a Driud.
![drupalaton_shot_1](https://cloud.githubusercontent.com/assets/1001383/26780993/912f3cd4-49ec-11e7-8e6c-98e3c764fc74.png)

**Comment by zsofimajor** [comment]
Megjavult, szupigó!

http://4.bp.blogspot.com/-qUVb2htmzuo/UgY3eJkjNdI/AAAAAAAAE9o/oYfq5UNe2sk/s400/its-magic-shia-labeouf-gif.gif
