### ISSUE TITLE
Room booking @Annabella - formázás

### ISSUE THREAD

**Issue by zsofimajor** [Drupalaton/drupalaton_profile#48]
A http://2017.drupalaton.hu/accomodation oldalon a következő bekezdést meg kéne formázni:

The Drupalaton attendees receive a special discount from the hotel. 
Please fill in the following reservation form: http://bit.ly/drupalaton2017_annabella_reservation and send back to the annabella.sales@danubiushotels.com email address with the following subject: ‘Drupalaton room reservation’ to get special discount prices for the period of 10-13 August 2017.

Az első sor title, legyen.
A form link kaphatna egy buttont, stb.
Az egészet rakjátok be kérlek egy dobozba, diszkrét szürke háttérrel, hogy kiemelődjön.

**Comment by segi** [comment]
Kint.
