### ISSUE TITLE
Eloadas javaslatbol session CT es uj user

### ISSUE THREAD

**Issue by yorkhu** [Drupalaton/drupalaton_profile#6]
Ha elfogadunk egy eloadas javaslatot akkor az entityform elembol jojjon letre egy session CT es egy user. A user tudja szerkeszteni a hozza tartozo sessiont. (Ha tobb eloado van akkor kezzel letrehozzuk a tars eloadot, de o is tudja szerkeszteni a sessiont.)

**Comment by csakiistvan** [comment]
ez kész?

**Comment by yorkhu** [comment]
Elm. igen, azt meg le kell probalni, hogy a user tudja-e szerkeszteni a sajat contentjet.

**Comment by csakiistvan** [comment]
pusholtam, eddig nem tudta, kérlek ellenőrizd

**Comment by yorkhu** [comment]
Elso ranezesre jo :).
